### ISSUE TITLE
Bug, not sure how to describe it.

### ISSUE THREAD

**Issue by fernandodiacenco** [Matt-Deacalion/Pomodoro-Calculator#15]
Hello,

On Ubuntu 18.04 after installing pip and pomogoro-calculator, using the following syntax the output is:

**get-pomodori -f=8:30 17:30**

> Traceback (most recent call last):
>   File "/usr/local/bin/get-pomodori", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/pomodoro_calculator/main.py", lin                                                                               e 107, in main
>     interval=arguments['--interval'],
>   File "/usr/local/lib/python2.7/dist-packages/pomodoro_calculator/__init__.py",                                                                                line 24, in __init__
>     self.start = self._create_datetime(start)
>   File "/usr/local/lib/python2.7/dist-packages/pomodoro_calculator/__init__.py",                                                                                line 80, in _create_datetime
>     [int(unit) for unit in time_string.split(':')],
> ValueError: invalid literal for int() with base 10: '=8'

I'm not sure if i'm using it wrong, also is there any plans for a web version of this tool? Thanks.

**Comment by Matt-Deacalion** [comment]
Hi Fernando,

The correct syntax would be either of the following:

`get-pomodori --from=8:30 17:30` OR `get-pomodori -f 8:30 17:30`

All the best.
