### ISSUE TITLE
Can't get --group to work

### ISSUE THREAD

**Issue by avibrown** [Matt-Deacalion/Pomodoro-Calculator#17]
Hi, first of all thanks for making this! It was exactly what I was after.

I'm trying to change the number of pomodoros before long breaks but nothing I'm trying seems to work. Can you give an example of how to do it?

I've tried:
`get-pomodori --group=3`
`get-pomodori --group 3`
`get-pomodori --group=<3>`
`get-pomodori [--group=<3>]`
`get-pomodori --group=3`

etc.

**Comment by Matt-Deacalion** [comment]
Hi Avi, thank you!

You can either choose how many pomodori you want to do with the ``--amount`` flag, like this (**7** pomodori with a **long** break every third pomodoro):

![pomodoro-amount](https://user-images.githubusercontent.com/1128480/170881805-4f669add-ff2e-439c-98de-61da43771844.png)

Or you can specify an **end** time and the number of pomodori will be worked out automatically, like this:

![pomodoro-end-time](https://user-images.githubusercontent.com/1128480/170881808-bc5cb4dd-536a-4c87-9a94-a32fe6003af0.png)

**Comment by avibrown** [comment]
Ahh, got it. I thought it was possible to change the settings without passing an end time. How can I go about changing the default values so that I don't have to type it in each time? For some reason having trouble finding where the files are stored! Haha

**Comment by Matt-Deacalion** [comment]
At the moment the default values are hard coded, [here](https://github.com/Matt-Deacalion/Pomodoro-Calculator/blob/fd426f479748826b4987f9037483686da5e344ec/pomodoro_calculator/__init__.py#L17-L18). Adding a way for users to override this would be a nice feature, maybe through shell environment variables. In the mean time, if you're using Bash... you could create an alias by adding something like this to your `~/.bashrc`:

``alias get-pomodori='get-pomodori --group 3'``

Now the ``get-pomorodi`` command will default to a long break after every **third** pomodoro. For example, you can run ``get-pomodori --amount 10`` without specifiying ``--group 3``.

**Comment by avibrown** [comment]
Great, thanks Matt!
